"""Write docs/lightburn-kit/test-vectors.json: byte-exact examples for an independent implementation.

Everything is produced by this package's encoders, which are verified on hardware (an Omni Xe 6W,
see docs/hardware-testing.md). tests/test_vectors.py fails if the file is out of date.
"""

from __future__ import annotations

import json
import struct
from pathlib import Path

from omni_autofocus import __version__, commands, config, flash, framing, modbus

OUT = Path(__file__).resolve().parent.parent / "docs" / "lightburn-kit" / "test-vectors.json"


def hx(b: bytes) -> str:
    return b.hex(" ")


def cmd_frame(payload: bytes) -> str:
    return hx(framing.build_frame(payload, seq=framing.seq_byte(command_port=True, seq=0)))


def data_frame(payload: bytes, seq: int = 1) -> str:
    return hx(framing.build_frame(payload, seq=framing.seq_byte(command_port=False, seq=seq)))


def modbus_reply(micrometres: int) -> bytes:
    return modbus.with_crc(bytes([1, 4, 4]) + struct.pack(">I", micrometres))


def build() -> dict:
    z = config.ZAxisSettings().axis_params()  # Omni Xe 6W: axis 1, 3200 pulses/rev, 4 mm/rev, reversed
    moves = {}
    for mm in (1.0, -1.0, 17.0):
        pulses = z.mm_to_pulses(mm)
        lst = commands.command_list(commands.axis_move_cmd(z, pulses), commands.delay_cmd(1))
        moves[f"{mm:+g} mm"] = {
            "pulses": pulses,
            "list_payload": hx(lst),
            "data_port_frame_seq1": data_frame(lst),
        }
    load = struct.pack(">HBB", flash.CMD_FLASH_LOAD, 1, 0) + struct.pack(">II", flash.CHUNK, 0x1000)
    return {
        "about": (
            "Byte-exact examples for the ComMarker Omni X/Xe (BSL Executor7, USB 04B4:1004). Generated by "
            f"omni-autofocus {__version__}, whose encoders are verified on an Omni Xe 6W. Hex bytes are "
            "space-separated. 'frame' = what goes over USB; 'payload' = the command inside it."
        ),
        "framing": {
            "rule": "FE FF | BE u16 total length | seq byte | status | payload padded to even, >= 12 | 00 | "
            "checksum = (b[6] + b[7] + b[N-4] + b[N-3]) & 0xFF",
            "command_port": "OUT 0x06 / IN 0x88, seq byte 0x80 (sequence always 0)",
            "data_port": "OUT 0x02 / IN 0x84, seq byte 0x01..0x0F cycling; ack payload starts FA 01",
        },
        "state_queries": {
            "AA05 device state": cmd_frame(commands.status_cmd(commands.CMD_DEV_STATE)),
            "AA07 extended state (axis counters)": cmd_frame(commands.status_cmd(commands.CMD_DEV_EXT_STATE)),
        },
        "run_state": {
            "AA10 run (lists execute)": cmd_frame(commands.run_state_cmd(commands.RUN_STATE_RUN)),
            "AA10 reset": cmd_frame(commands.run_state_cmd(commands.RUN_STATE_RESET)),
        },
        "height_sensor": {
            "modbus_request": hx(commands.HEIGHT_REQUEST),
            "AAC1 send request": cmd_frame(commands.data_transmit(commands.HEIGHT_REQUEST)),
            "AAC1 collect (after ~200 ms)": cmd_frame(commands.data_transmit(b"")),
            "AAC1 reply layout": "reply payload: [0..1] echo AA C1, [2] bytes received, [4..] Modbus frame",
            "modbus_reply_examples": {
                "222.000 mm": hx(modbus_reply(222_000)),
                "181.500 mm": hx(modbus_reply(181_500)),
                "no surface in range (observed on hardware)": "01 04 04 7f ff ff ff d3 d0",
            },
            "decode": "distance_mm = BE u32 of the 4 register bytes / 1000; 0x7FFFFFFF = no measurement",
        },
        "z_moves": {
            "axis": "auxiliary axis 1, 800 pulses/mm, bRevRot = true, run 8 mm/s, accel 5 mm/s^2, start 0",
            "sequence": "AA10 reset, 10 ms, AA10 run, list [03A0 move, 0A00 delay(1)] on the data port, poll "
            "AA05 until reply[12] bit0 set (or state <= 1), wait for the AA07 moving bit to clear, AA10 "
            "reset (or back to run if another program had the board in run state)",
            "moves": moves,
        },
        "factory_calibration": {
            "AAE0 user-area range": cmd_frame(commands.status_cmd(flash.CMD_FLASH_INFO)),
            "AAE1 flash state": cmd_frame(commands.status_cmd(flash.CMD_FLASH_STATE)),
            "AAE4 load 480 bytes at user-area offset 0x1000": cmd_frame(load),
            "AAE5 fetch buffer": cmd_frame(commands.status_cmd(flash.CMD_FLASH_FETCH)),
            "check_values": {
                "store crc16('123456789')": f"0x{flash.crc16(b'123456789'):04x}",
                "crc64_ecma182('123456789')": f"0x{flash.crc64(b'123456789'):016x}",
            },
            "cfg_xor_key": hx(config.COMMARKER_XOR_KEY),
            "focus_keys": "lmcPars.params[parName=default].fBestFocalDistance (lens A) / "
            "fBestFocalDistance_B (lens B), in sensor mm",
        },
    }


def render() -> str:
    return json.dumps(build(), indent=2) + "\n"


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
